/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as InnovationPartnersRouteImport } from './routes/innovation-partners'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SolutionsQrTechnologyRouteImport } from './routes/solutions.qr-technology'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminCareersRouteImport } from './routes/admin/careers'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationPartnersRoute = InnovationPartnersRouteImport.update({
  id: '/innovation-partners',
  path: '/innovation-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsQrTechnologyRoute = SolutionsQrTechnologyRouteImport.update({
  id: '/qr-technology',
  path: '/qr-technology',
  getParentRoute: () => SolutionsRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/admin/careers',
  path: '/admin/careers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/careers': typeof CareersRoute
  '/contact-us': typeof ContactUsRoute
  '/innovation-partners': typeof InnovationPartnersRoute
  '/insights': typeof InsightsRoute
  '/products': typeof ProductsRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/admin/careers': typeof AdminCareersRoute
  '/admin/login': typeof AdminLoginRoute
  '/solutions/qr-technology': typeof SolutionsQrTechnologyRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/careers': typeof CareersRoute
  '/contact-us': typeof ContactUsRoute
  '/innovation-partners': typeof InnovationPartnersRoute
  '/insights': typeof InsightsRoute
  '/products': typeof ProductsRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/admin/careers': typeof AdminCareersRoute
  '/admin/login': typeof AdminLoginRoute
  '/solutions/qr-technology': typeof SolutionsQrTechnologyRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/careers': typeof CareersRoute
  '/contact-us': typeof ContactUsRoute
  '/innovation-partners': typeof InnovationPartnersRoute
  '/insights': typeof InsightsRoute
  '/products': typeof ProductsRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/admin/careers': typeof AdminCareersRoute
  '/admin/login': typeof AdminLoginRoute
  '/solutions/qr-technology': typeof SolutionsQrTechnologyRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/careers'
    | '/contact-us'
    | '/innovation-partners'
    | '/insights'
    | '/products'
    | '/solutions'
    | '/admin/careers'
    | '/admin/login'
    | '/solutions/qr-technology'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/careers'
    | '/contact-us'
    | '/innovation-partners'
    | '/insights'
    | '/products'
    | '/solutions'
    | '/admin/careers'
    | '/admin/login'
    | '/solutions/qr-technology'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/careers'
    | '/contact-us'
    | '/innovation-partners'
    | '/insights'
    | '/products'
    | '/solutions'
    | '/admin/careers'
    | '/admin/login'
    | '/solutions/qr-technology'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  CareersRoute: typeof CareersRoute
  ContactUsRoute: typeof ContactUsRoute
  InnovationPartnersRoute: typeof InnovationPartnersRoute
  InsightsRoute: typeof InsightsRoute
  ProductsRoute: typeof ProductsRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  AdminCareersRoute: typeof AdminCareersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation-partners': {
      id: '/innovation-partners'
      path: '/innovation-partners'
      fullPath: '/innovation-partners'
      preLoaderRoute: typeof InnovationPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/qr-technology': {
      id: '/solutions/qr-technology'
      path: '/qr-technology'
      fullPath: '/solutions/qr-technology'
      preLoaderRoute: typeof SolutionsQrTechnologyRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/admin/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SolutionsRouteChildren {
  SolutionsQrTechnologyRoute: typeof SolutionsQrTechnologyRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsQrTechnologyRoute: SolutionsQrTechnologyRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  CareersRoute: CareersRoute,
  ContactUsRoute: ContactUsRoute,
  InnovationPartnersRoute: InnovationPartnersRoute,
  InsightsRoute: InsightsRoute,
  ProductsRoute: ProductsRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  AdminCareersRoute: AdminCareersRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
